services:
  authentication-db:
    image: postgres:15-alpine
    container_name: authentication-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "parcel_auth"
      POSTGRES_PASSWORD: "ParcelAuth2025@"
      POSTGRES_DB: "Authentication"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  parcel-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: parcel-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ParcelApi2025@"
  
  authentication:
    image: authentication.api
    build:
      context: .
      dockerfile: Services/Auth/Authentication/Dockerfile
    ports:
      - "3333:3333"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3333
    depends_on:
      - authentication-db
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro

  parcel:
    image: parcel.api
    build:
      context: .
      dockerfile: Services/Parcel/Parcel.API/Dockerfile
    ports:
      - "1111:1111"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:1111
    depends_on:
      - parcel-db
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro

volumes:
  postgres_data: