services:
  postgres-db:
    image: postgres:15-alpine # Use PostgreSQL 15 Alpine image
    container_name: postgres-db
    ports:
      - "5432:5432" # Expose PostgreSQL on default port
    environment:
      POSTGRES_USER: "parcel_auth"
      POSTGRES_PASSWORD: "ParcelAuth2025@"
      POSTGRES_DB: "Authentication"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for database data
  
  authentication:
    image: authentication
    build:
      context: .
      dockerfile: Services/Auth/Authentication/Dockerfile
    ports:
      - "3333:3333" # Map container's port 3333 to host port 3333
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3333 # Ensure app listens on port 3333
    depends_on:
      - postgres-db # Ensure PostgreSQL starts before this service
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro

volumes:
  postgres_data: # Define a named volume for PostgreSQL persistence